include $(CLEAR_VARS)
LOCAL_MODULE := SMSOrganizer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := SMSOrganizer/smsorganizer.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Messages
include $(BUILD_PREBUILT)
